import { environment } from "../../environments/environment";
export const RouterPath: any = {
  root: environment.routeSubpath,
  login: environment.routeSubpath + "login",
  forgetpassword: environment.routeSubpath + "forget-password",
  forgetcomplete: environment.routeSubpath + "complete",
  resetpassword: environment.routeSubpath + "reset-password",
  register: environment.routeSubpath + "registration",
  registercomplete: environment.routeSubpath + "register-completed",
  customer: environment.routeSubpath + "customer",
  quotation: environment.routeSubpath + "quotation",
  order: environment.routeSubpath + "order",
  purchase: environment.routeSubpath + "purchase",
  accounting: environment.routeSubpath + "accounting",
  warehouse: environment.routeSubpath + "warehouse",
  report: environment.routeSubpath + "report",
  setting: environment.routeSubpath + "setting",
  payment: "payment",
  shipping: "shipping",
  stock: "stock",
  product: "product",
  vendor: "vendor",
  account: "account",
  seller: "seller",
  customertask: environment.routeSubpath + "viewtask",
  customertaskdetail: environment.routeSubpath + "viewtaskdetail",
};
