const mongoose = require("mongoose"),
  Schema = mongoose.Schema;

const modelSchema = new Schema({
  _id: mongoose.Schema.Types.ObjectId,
  quotation_code: { type: String },
  customer_code: { type: String },
  customer_name: { type: String },
  customer_type: { type: String },
  dealer: { type: String },
  email: { type: String },
  line: { type: String },
  note: { type: String },
  payment_remark: { type: String },
  payment_type: { type: String },
  phone: { type: String },
  customer_remark: { type: String },
  shipping_detail: { type: String },
  shipping_type: { type: String },
  tax_address: { type: String },
  tax_id: { type: String },
  // product: [{ type: Object }],
  // sub_product: [{ type: Object }],
  total_quantity: { type: Number },
  total_price: { type: Number },
  remark: { type: String },
  status: { type: String }, // รออนุมัติ, อนุมัติแล้ว, หมดอายุ, ยกเลิก
  document_type: { type: String }, //q = quotation, j = product, po = purchase
  document_reference: { type: String },
  onprogress_date: { type: Date },
  illustration: { type: String },
  customer_id: mongoose.Schema.Types.ObjectId,
  ref_quotation_id: mongoose.Schema.Types.ObjectId,
  ref_quotation_ids: [mongoose.Schema.Types.ObjectId],
  seller_id: mongoose.Schema.Types.ObjectId,
  seller_name: { type: String },
  seller_type: { type: String },
  seller_dealer: { type: String },
  seller_email: { type: String },
  seller_line: { type: String },
  seller_note: { type: String },
  seller_payment_remark: { type: String },
  seller_payment_type: { type: String },
  seller_phone: { type: String },
  seller_remark: { type: String },

  cancel_remark: { type: String },
  created: { type: Date },
  modified: { type: Date },
  approved: { type: Date },
  createdby: { type: String },
  modifiedby: { type: String },
  approvedby: { type: String },
  created_role: { type: String },
  modified_role: { type: String },
  approved_role: { type: String },
});
module.exports = mongoose.model("bww_quotations", modelSchema);
