export * from './customer.component';
export * from './customer-manage/customer-manage.component';
export * from './customer-detail/customer-detail.component';
export * from './customer-attachment/customer-attachment.component';
export * from './customer-sharelink/customer-sharelink.component';
export * from './customer-new/customer-new.component';
export * from './customer-complete/customer-complete.component';
export * from './customer-inprogress/customer-inprogress.component';
export * from './customer-viewtask/customer-viewtask.component';
